name: Venkat Rajneesh
title: Venkat Rajneesh
author: Venkat Rajneesh
url: https://rajneesh4500.github.io

tagline: Rajneesh's blog to pass the time.
description: I am Rajneesh working as Software Development Engineer 2 at Oracle, India. I work on Linux Device Drivers, Systems / Kernel Programming & Embedded Systems.

twitter:
    username: rajneesh4500
    card: summary

github: https://github.com/rajneesh4500
linkedin: https://www.linkedin.com/in/rajneesh4500/
theme:

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title/
collections:
  posts:
    permalink: /blog/:title/

compress_html:
  clippings: all 
  comments: all
  endings: []
  profile: false
  blanklines: false
  ignore:
    envs: []